apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  kustomize.generated.resource: "true"
bases:
  - ../../base
images:
  - name: allegroai/trains-server
    newTag: "0.14"
